import { isSignInWithEmailLink, onAuthStateChanged, signInWithEmailLink, signOut, type User } from "firebase/auth";
import { auth } from "@/lib/firebase/client";
import { generateSignInLinkAction } from "@/app/(auth)/actions";
import { sendSignInEmail } from "@/lib/email/emailjs";

const STORED_EMAIL_KEY = "miles-and-smiles:signInEmail";

/**
 * Sends a passwordless sign-in link to the given email, landing back on /account/verify.
 * The link is generated by Firebase (Admin SDK) but delivered via EmailJS instead of
 * Firebase's own mailer, so branding/deliverability is ours to control.
 */
export async function requestSignInLink(email: string) {
  const link = await generateSignInLinkAction(email);
  await sendSignInEmail({ toEmail: email, link });
  window.localStorage.setItem(STORED_EMAIL_KEY, email);
}

/** Completes sign-in from the link the member clicked. Call this on /account/verify. */
export async function completeSignInFromLink(fallbackEmail?: string): Promise<User> {
  if (!isSignInWithEmailLink(auth, window.location.href)) {
    throw new Error("This link is invalid or has expired.");
  }

  const email = window.localStorage.getItem(STORED_EMAIL_KEY) ?? fallbackEmail;
  if (!email) {
    throw new Error("EMAIL_REQUIRED");
  }

  const credential = await signInWithEmailLink(auth, email, window.location.href);
  window.localStorage.removeItem(STORED_EMAIL_KEY);
  return credential.user;
}

export function subscribeAuthState(cb: (user: User | null) => void) {
  return onAuthStateChanged(auth, cb);
}

export async function signOutMember() {
  await signOut(auth);
}
